@echo off
set /p ubicacion=NOMBRE-UBICACION:
echo HOSTNAME: %computername% >> "%ubicacion%.txt"
echo MARCA >> "%ubicacion%.txt"
wmic csproduct get vendor >> "%ubicacion%.txt"
echo MODELO >> "%ubicacion%.txt"
wmic csproduct get name >> "%ubicacion%.txt"
echo NUMERO SERIE >> "%ubicacion%.txt"
wmic bios get serialnumber >> "%ubicacion%.txt"
echo MAC >> "%ubicacion%.txt"
getmac >> "%ubicacion%.txt"
echo PROCESADOR >> "%ubicacion%.txt"
WMIC /Output:STDOUT CPU get Name >> "%ubicacion%.txt"
echo DISCO DURO >> "%ubicacion%.txt"
wmic diskdrive get Caption,size,MediaType >> "%ubicacion%.txt"
echo RAM >> "%ubicacion%.txt"
wmic MemoryChip get Capacity,PositionInRow >> "%ubicacion%.txt"
echo VERSION WINDOWS >> "%ubicacion%.txt"
wmic os get Caption >> "%ubicacion%.txt"
echo VERSION OFFICE >> "%ubicacion%.txt"
reg query "HKEY_CLASSES_ROOT\Word.Application\CurVer" >> "%ubicacion%.txt"
